### ISSUE TITLE
Settings for the extension

### ISSUE THREAD

**Issue by d0325mgray** [josephlacey/com.jlacey.electoral#10]
On the settings page for the extension, there are fields for state, country and city. If I want to include all states, do I just leave the field blank or do I have to list all 50 states?

**Comment by josephlacey** [comment]
While admittedly a bit laborious, yes, you need to whitelist all the states you'd like to include in the districting and the reps Scheduled Jobs..  I opted for this approach, so there was better predictability and testability.
