### ISSUE TITLE
Results returned by the extension

### ISSUE THREAD

**Issue by d0325mgray** [josephlacey/com.jlacey.electoral#11]
I see the extension is adding a contact for the representatives it finds in a district. What I want do do is add the district to the voting address records for a contact. So far, I haven't seen it doing that.

**Comment by josephlacey** [comment]
Each electoral level should have both a representatives Scheduled Job and a districts Scheduled Job, e.g. `Google Civic Information API - State and Province Representatives` and `Google Civic Information API - State and Province Districts`.  To add districts to contacts, you'll want to enable the latter.

**Comment by d0325mgray** [comment]
It is enabled and runs daily. How can I confirm results?

**Comment by josephlacey** [comment]
The log for the scheduled job should show a minimal output of how many addresses it processed and what the result was.  You can also search for contacts that now have district information.  I've found the more sophisticated operators in the Search Builder best for this.

**Comment by d0325mgray** [comment]
The Search Builder did the trick. Thanks
