### ISSUE TITLE
Multiple Main Addresses for Representatives

### ISSUE THREAD

**Issue by d0325mgray** [josephlacey/com.jlacey.electoral#14]
I took a look at a couple of California reps, Salud Carbajal and Adam Schiff. Each has at least ten address entries for the main address.  It seems like an address is added each time the job is run

**Comment by jimcrist** [comment]
I'm not having that problem with constituents in Wisconsin state districts.

**Comment by josephlacey** [comment]
@d0325mgray The representatives job you should only need to run once.  It doesn't need to be enabled to run periodically with cron.  Although perhaps I'm not aware a particular workflow?

**Comment by d0325mgray** [comment]
Reps do change. They resign, die or,  sometimes get thrown in jail. I thought running it periodically would update those changes, , not keep adding duplicate address records for existing reps

**Comment by josephlacey** [comment]
> Reps do change. They resign, die or, sometimes get thrown in jail. I thought running it periodically would update those changes, , not keep adding duplicate address records for existing reps

Sure, but automatically keeping up with these changes has never been added to this extension.

**Comment by d0325mgray** [comment]
Is there a wish list of features, in case anyone wants to work on this extension again?
