### ISSUE TITLE
Add readme.md with instructions

### ISSUE THREAD

**Issue by joemcl** [josephlacey/com.jlacey.electoral#21]
Hi @josephlacey ! Thanks so so much for updating this since last we met, in St. Louis I think at the Civicon and sprint in 2017. 
I've installed this on a new demo site, found where to add the Google Civic and ProPublica API keys. It's been awhile - a couple of years - since I last used this. 
I'm not seeing how to set up a Scheduled Job to run the API calls. 
Can you please add basic instructions re installation and use to a readme.md doc? 
Thanks so much!

**Comment by joemcl** [comment]
See #22

**Comment by josephlacey** [comment]
@joemcl I commented on the PR request about next steps.  Also nice to hear from you again.  I hope things have been well.

**Comment by joemcl** [comment]
see #24 . it's a very basic start. @MegaphoneJon @twomice aditional readme PRs *very* much appreciated :) . TBH @josephlacey why don't we get this repo over on lab.civcrm.org - totally appreciate that your interest in this has waned, and your available time, but this is a hugely useful extension that the community can continue to build on more easily at lab.civicrm.org .

**Comment by josephlacey** [comment]
> see #24 . 

Merged, so I'm going to close this.

> TBH @josephlacey why don't we get this repo over on lab.civcrm.org - I totally appreciate that your interest in this has waned, and your available time. This is a hugely useful extension that the community can continue to build on more easily at lab.civicrm.org .

I'll look into that, but my experience is the opposite.  Folks say they want this functionality, but I've only ever heard of a handful of folks actually using it.  That might be a reflection of the limitations of the current state of this extension, but I also wonder if it reflects that this kind of digital organizing has some fundamental limitations.

**Comment by joemcl** [comment]
@josephlacey I hear you. Part of the challenge I think is that there is not a lot of documentation, the  upgrade/re-install process is tedious and kind of a challenge, the repo was/is lacking a description, it's not listed in the CiviCRM Extensions list. Some of these things might be easier for folks to collaborate on over at lab.civicrm.org . As far as interest in using it, based on the number of downloads of the similar but now-deprecated Sunlight API Drupal module, there seems to be interest - see https://www.drupal.org/project/cd_sunlight . Perhaps the folks at democrats.com are interested in helping to fund updating this, and I think there are other potential funders, like me for one :) .

**Comment by josephlacey** [comment]
> @josephlacey I hear you. Part of the challenge I think is that there is not a lot of documentation, the upgrade/re-install process is tedious and kind of a challenge, the repo was/is lacking a description, it's not listed in the CiviCRM Extensions list. Some of these things might be easier for folks to collaborate on over at lab.civicrm.org . As far as interest in using it, based on the number of downloads of the similar but now-deprecated Sunlight API Drupal module, there seems to be interest - see https://www.drupal.org/project/cd_sunlight . Perhaps the folks at democrats.com ( hi @dhornbein @dalin- ) are interested in helping to fund updating this, or collaborating on PRs, and I think there are other potential funders, like me, for one :) .

Sure, these are all fair criticisms, some perhaps anachronistic, but honestly I never finished the extension because I couldn't get the folks I wrote it for to use it for even minimal testing.  Was not publishing it more widely, regardless of that reception, a mistake?  Perhaps.  But I also interpreted that as a judgment on the useful this extension has for folks organizing against people and institutions of power.  Downloads are one metric, but efficacy is another, and the latter just didn't seem to be there.
