### ISSUE TITLE
Level, city, chambers don't appear in UI after upgrade/reinstall 

### ISSUE THREAD

**Issue by joemcl** [josephlacey/com.jlacey.electoral#25]
See the last comments in #23. I'm running this on Civi 5.18.3 and Drupal 7.67. After re-installing, Level, City and Chambers labels do not appear in the user interface, even though the labels are in a record. District numbers do show in the UI. Screenshots below. 

![CiviElectoralDistricts-Joe-20191120-933PMPacific](https://user-images.githubusercontent.com/3912434/69439689-55dc1500-0cfc-11ea-9053-f2c6a9b4cb89.jpeg)

![CiviElectoralJoeDistrictsAPIExplorer](https://user-images.githubusercontent.com/3912434/69439745-6c826c00-0cfc-11ea-819f-6d427d7e2a46.jpeg)

**Comment by jimcrist** [comment]
Here's how it looks in WordPress and Civi 5.15.1
![image](https://user-images.githubusercontent.com/30061283/69445625-b54c1c00-0d20-11ea-8786-e382dd336c26.png)

**Comment by joemcl** [comment]
Thanks @jimcrist, yeah when I removed fields to do a reinstall, something didn't get reinstalled that adds the labels back in. Did you get it working after a reinstalll, doing similar to steps I did in #23 ?

**Comment by joemcl** [comment]
And @jimcrist have you run city, county level Scheduled Jobs?

**Comment by joemcl** [comment]
Also Country level, to populate Congressional district and Senate?

**Comment by joemcl** [comment]
And actually, @josephlacey, I need to add City name to the API settings to populate that? Looks like the fourth line in my screenshot is actually US Senate.

**Comment by jimcrist** [comment]
@joemcl Yes, I did similar steps which I summed up in my post yesterday.  It seemed to go better than what you're experiencing.  My biggest problem was a bug in the code that has since been fixed.  I'm only using it at the state level here in Wisconsin, tho I plan on using it at the federal level as well for Wisconsin's Congress Critters.

**Comment by josephlacey** [comment]
> After re-installing, Level, City and Chambers labels do not appear in the user interface, even though the labels are in a record.

@joemcl Something must have gone awry during the reinstall.  Level and Chambers are just standard option groups, which you can find if you go to Administer > System Settings > Option Groups.  

Level has four options upon install

- Country | country
- State/Province | administrativeArea1
- County | administrativeArea2
- City | locality

Chamber has two options upon install

- Upper | upper
- Lower | lower

Presumably if you add these back in or correct them somehow, the labels should appear in the UI.

City is a text field as their is no exhaustive list of cities.

**Comment by josephlacey** [comment]
> And actually, @josephlacey, I need to add City name to the API settings to populate that?

Yes, unlike counties and states, there isn't a list of cities we can provide to select from.  If you want to use the City jobs, you have to enter them comma separated into the settings page.  And they have to match what Google uses.

**Comment by joemcl** [comment]
hmm @josephlacey that seems pretty tedious. So if I want to add electoral districts for all my contacts in say, one state, including say City Council, for which I have an address, then I have to enter a comma-delimited list of *every city in the state*? Even though I have City in the address already?  Yikes.

**Comment by josephlacey** [comment]
> hmm @josephlacey that seems pretty tedious. So if I want to add electoral districts for all my contacts in say, one state, including say City Council, for which I have an address, then I have to enter a comma-delimited list of _every city in the state_? Even though I have City in the address already? Yikes.

@joemcl The original use case for the current version was to look up city council data for a subset of cities in a the client's data set, not all of them, so I wrote it assuming limitations.  Having it run through all the cities in a given data set would probably be pretty straightforward with a checkbox on the settings page and some alterations to the code.  PR's welcome.

**Comment by joemcl** [comment]
@josephlacey re the Option Groups, they are already there, and so apparently added back on re-install, see screenshots below. But those label values aren't being populated into a record. Hmm. So I'm gonna try adding them in again in the existing Option Groups manually. 

![CiviElectoralOptionGroupLevel](https://user-images.githubusercontent.com/3912434/69453176-3357f500-0d18-11ea-828f-30f20e2f314c.jpeg)
![CiviOptionGroupFieldsChamber](https://user-images.githubusercontent.com/3912434/69453184-381ca900-0d18-11ea-8eef-7cb0fed03987.jpeg)

**Comment by josephlacey** [comment]
> @josephlacey re the Option Groups, they are already there, and so apparently added back on re-install, see screenshots below. But those label values aren't being populated into a record. Hmm. So I'm gonna try adding them in again in the existing Option Groups manually.

Caching?

**Comment by joemcl** [comment]
> > hmm @josephlacey that seems pretty tedious. So if I want to add electoral districts for all my contacts in say, one state, including say City Council, for which I have an address, then I have to enter a comma-delimited list of _every city in the state_? Even though I have City in the address already? Yikes.
> 
> @joemcl The original use case for the current version was to look up city council data for a subset of cities in a the client's data set, not all of them, so I wrote it assuming limitations. Having it run through all the cities in a given data set would probably be pretty straightforward with a checkbox on the settings page and some alterations to the code. PR's welcome.

OK got it. Same would apply for all states in a country, all counties in a state,etc.

**Comment by joemcl** [comment]
@josephlacey sorry by `Caching` you mean run Administer -> System Settings -> Cleanup Caches? Have done that, yeah, will again. Do you mean settings on Scheduled Jobs, like I should set `update=1` not `update=0`?

**Comment by josephlacey** [comment]
> @josephlacey sorry by `Caching` you mean run Administer -> System Settings -> Cleanup Caches? 

Hmm, yeah, I meant this one.  Are the options available when you click the pencil to manually edit the fields?

**Comment by joemcl** [comment]
> > @josephlacey sorry by `Caching` you mean run Administer -> System Settings -> Cleanup Caches?
> 
> Hmm, yeah, I meant this one. Are the options available when you click the pencil to manually edit the fields?

You mean manually edit the fields in a record - no, so Chamber just shows -none- for example. Same thing in Advanced Search dropdowns.

**Comment by joemcl** [comment]
hi @josephlacey @twomice - I think the error I'm getting above is the same as in #19.

**Comment by joemcl** [comment]
FYI I've made some progress in trying to restore the functionality of the extension to where it was before I somewhat ham-handedly removed fields using the API - I'm still trying to get City, County and State/Province back in Summary fields when editing an Address. See the latest comments in the Stack Exchange Q and A at `https://civicrm.stackexchange.com/questions/33833/how-do-i-restore-city-county-state-to-the-address-block-in-contact-summary`.

**Comment by joemcl** [comment]
OK closing this. As @MegaphoneJon helped me figure out, the problem is that I was installing/uninstalling as the wrong user :(  and that caused the problem.
