### ISSUE TITLE
Fresh install didn't work...

### ISSUE THREAD

**Issue by jimcrist** [josephlacey/com.jlacey.electoral#35]
Hi, I did a fresh install of CiviCRM 5.37.2 on a WordPress website it's working fine.  I just downloaded and installed the current version of this extension and it gave me DB Error: unknown error, so I restored everything and tried again and got the same result. It seems to create all the tables and everything and CiviCRM still works sort of, but when I try to bring up a contact it says DB Error: no such field. It produced a lot in the ConfigAndLog file...here's the first part...please help!!
PHP 7.3 and MySQL is MariaDB 10.1 

`Jul 25 15:07:41  [error] $Fatal Error Details = Array
(
    [callback] => Array
        (
            [0] => CRM_Core_Error
            [1] => exceptionHandler
        )

    [code] => -1
    [message] => DB Error: unknown error
    [mode] => 16
    [debug_info] =>         ALTER TABLE civicrm_value_electoral_status_2
        ADD COLUMN `electoral_status_error_reason` varchar(255),
        ADD INDEX INDEX_electoral_status_error_reason ( electoral_status_error_reason ) [nativecode=1709 ** Index column size too large. The maximum column size is 767 bytes.]
    [type] => DB_Error
    [user_info] =>         ALTER TABLE civicrm_value_electoral_status_2
        ADD COLUMN `electoral_status_error_reason` varchar(255),
        ADD INDEX INDEX_electoral_status_error_reason ( electoral_status_error_reason ) [nativecode=1709 ** Index column size too large. The maximum column size is 767 bytes.]
    [to_string] => [db_error: message="DB Error: unknown error" code=-1 mode=callback callback=CRM_Core_Error::exceptionHandler prefix="" info="        ALTER TABLE civicrm_value_electoral_status_2
        ADD COLUMN `electoral_status_error_reason` varchar(255),
        ADD INDEX INDEX_electoral_status_error_reason ( electoral_status_error_reason ) [nativecode=1709 ** Index column size too large. The maximum column size is 767 bytes.]"]
)
`

**Comment by josephlacey** [comment]
Hi @jimcrist,

This is sysadmin issue.  MariaDB needs to be configured to raise the index column limit that's mentioned in the error message.  You should contact your host.

Joseph

**Comment by jimcrist** [comment]
Cloudways wants to charge me at least $200 to customize their server 'cuz of this problem.  To make varchar(255) work. Why isn't 767 bytes enough?  Does this make sense to anyone? Is this related to utf8mb4?

**Comment by jimcrist** [comment]
Update: they did this and now it installs properly (I installed V3):

_| innodb_default_row_format | dynamic | ._

Should I have to pay to get that set right?
