### ISSUE TITLE
FEATURE REQUEST: Restore incumbent lookup for districts and show as a relationship

### ISSUE THREAD

**Issue by d0325mgray** [josephlacey/com.jlacey.electoral#37]
I would like to see the feature to create a record for incumbents restored. It has disappeared in v3.

In addition, I would like the extension to automatically create a relationship between the contact and the incumbents

**Comment by josephlacey** [comment]
@d0325mgray It might be confusing, but this original repository is just for v2.  If you'd like to make feature requests for v3, it's best to open those here,

https://github.com/MegaphoneJon/com.jlacey.electoral

And if you can help develop this feature with PR's or pay for someone's time to do so, I'm sure @MegaphoneJon would appreciate it.

**Comment by d0325mgray** [comment]
I am an individual with no budget for this kind of thing

**Comment by MegaphoneJon** [comment]
@d0325mgray Understood.  At some point, hopefully someone with a budget (or a coder) will step forward.
