### ISSUE TITLE
V3 Exceeded Queries per minute Quota

### ISSUE THREAD

**Issue by jimcrist** [josephlacey/com.jlacey.electoral#38]
I added 72 records to my little database (170 records total) and ran the scheduled job for Electoral Action: districts.  I'm asking for Wisconsin state districts and Congressional Districts.  In the Job Log, I'm getting the error: Quota exceeded for quota metric 'Queries' and limit 'Queries per minute

I looked at my Google Civic Info Account and didn't see anything wrong or anything helpful.  I know it worked when there were fewer records in the database.  Please advise...thanks!

**Comment by MegaphoneJon** [comment]
V3 questions should go on my repo for now - but - your query limits are dependent on when you got your API access.  I see in 2016 they were higher, but for at least the past year the default limit is 100 requests per 100 seconds.  Setting `limit=100` in your Districts scheduled job parameters will prevent this error.

**Comment by jimcrist** [comment]
I tried, but there's no issues tab on your repo: https://github.com/MegaphoneJon/com.jlacey.electoral
Your documentation indicates the default is limit=100, so I tried limit=50 and got the same error.  Just tried it again and it worked...go figure...

**Comment by MegaphoneJon** [comment]
Ah - thanks for pointing that out Jim, issues are available now.
