### ISSUE TITLE
Electoral API Settings Screen still refers to Sunlight Foundation

### ISSUE THREAD

**Issue by jimcrist** [josephlacey/com.jlacey.electoral#4]
Hi,
I'm trying to get a new API key from Open States. I noticed this screen still refers to Sunlight Foundation. That should be changed to Open States, right?

![image](https://user-images.githubusercontent.com/30061283/28931528-049d0f20-783c-11e7-8559-9006e780f1e0.png)

**Comment by josephlacey** [comment]
Indeed it should.  Thanks, Jim.

**Comment by josephlacey** [comment]
Deprecated with e3dfe935bf686849fd299b002c43b898ac0af215
