### ISSUE TITLE
Duplicate State District Records

### ISSUE THREAD

**Issue by jimcrist** [josephlacey/com.jlacey.electoral#5]
I'm using Open States API - Districts (Daily)
Adds state representative districts to contacts
API Entity: OpenStates
API Action: districts

One of our supporters moved, so I deleted their state district records. Waited a day. The scheduled job ran. It created 4 records instead of two, duplicating the upper and lower chamber records. I see this a lot. When I bring up a CiviCRM contact record, often there are 4 records instead of two. How come? Thanks for your work on this!
Jim

**Comment by josephlacey** [comment]
Hey Jim,

Yeah, duplicates are a known issue because of the way Civi's API handles custom data sets that allow multiple values.  I've got some new funding to improve the extension, so I'll keep this mind while I'm working through the rewrite and see if I can fix it.

Joseph

**Comment by josephlacey** [comment]
Fixed by 4c4fc94360026f987cf68fc6eec6130db4968bee
