### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by EddieConde** [josephlacey/com.jlacey.electoral#6]
Hi, thank you so much for making this API available. Is there some documentation about how to set it up and how to see the data on contacts available? 

I got my Google API Key entered on the Electoral API screen of CIVI, enabled Civic on Google, but I don't see anything new on the contact screen. Just need general information on how the end product should look like and how to start troubleshooting.

Thanks,
-Eddie

**Comment by d0325mgray** [comment]
I've got the same problem. I don't know how to set it up or get it to work.  EddieConde: did you ever figure it out? Nobody responded. I know how to get the CDs using Sunlight but I wanted to be able to make the process more automated

**Comment by EddieConde** [comment]
I did get it to work but I can't remember right now how I got it to work because I ended up ditching CIVI CRM altogether and haven't worked on it for a few months.

sorry I am not able to help.
