### ISSUE TITLE
Add district numbers to contact records - quit working

### ISSUE THREAD

**Issue by jimcrist** [josephlacey/com.jlacey.electoral#7]
Hi, I’ve been using this Extension for a long time in conjunction with the CiviCRM 4.7.20 database & WordPress website. It’s very valuable! I just noticed it quit working sometime after November 13, 2018. I’m getting the error when the cron job runs: “Finished execution of Open States API - Districts with result: Failure, Error message: ‘legislature’ is not a valid option for field custom_4”.  This is the description of the cron job:

Open States API - Districts (Daily)
Adds state representative districts to contacts
API Entity: OpenStates
API Action: districts

I'm only using this part of the API...for the state legislature in Wisconsin

Is this related to the new V2 from OpenStates?  How do I get this working again…thanks!!
Jim Crist

**Comment by jimcrist** [comment]
So now, after I posted this three days ago, the error message has changed to "Finished execution of Open States API - Districts with result: Failure, Error message: API (OpenStates, districts) does not exist".  But the OpenStates website indicates it's still supported. How do I get this working again...thanks!!

**Comment by josephlacey** [comment]
Hey Jim,

There are few possible variables here.  The first is that version 2 doesn't support the OpenStates API; instead it relies on Google's Civic Information API for districting.  If you've switched to version 2, you'll want to switch to the new Scheduled Jobs.  That does require getting a Google API key.  If you're using Google as your geocoding or mapping provider, you can reuse that same key.

If you haven't switched to version 2, which honestly might be fine, then there could have been a change with the OpenStates API.  I haven't been following the changes there though, so I can't say for sure.

Joseph

**Comment by jimcrist** [comment]
Hey Joseph,
Thanks for the reply.  Sorry I wasn't clear.  I'm still on V1.  I didn't want to go down the rabbit hole until I heard from you as to the best course of action.  You haven't been following the changes? That's scary.  Is this extension working for anyone? Is anyone going to maintain this extension? I'm not clear on how to try V2, either.  I have a Google API Key and am using it for geocoding. How do I switch to the new Scheduled Jobs?  Do I uninstall and reinstall your Extension?  Thanks for your help...jim

**Comment by josephlacey** [comment]
Hi Jim,

When [the Sunlight Foundation announced they would be closing their development and maintenance of the APIs](https://sunlightfoundation.com/api/), I started the process of switching to a new suite.  I settled on Google's.  I was contracted this past summer to write that integration, which comprises the bulk of version 2.  I also did a code restructuring and dealt with the duplicate custom field issue, #5.  My final set of testing showed that version 2 was working.

But that client decided not to use the rewrite, which is honestly in line with the lack of sustained interest in this extension over the years, both in usage and a willingness to pay me to maintain it.  And like all free software I don't make any guarantees.

There is no tested upgrade path between version 1 and 2.  Uninstalling version 1 and then installing version 2 might be totally fine, but I suspect the custom data fields from version 1 will turn out to be a problem.  I don't delete those when you uninstall the extension; installing version 2 might then throw an error when it tries to create them.  And the new Scheduled Jobs might not find the old custom fields correctly.  

You could uninstall version 1, delete the custom fields (thus losing all the data in those custom fields, so beware), install version 2 (which will recreate the empty fields) and then redistrict  all your contacts.  I'm not sure how many contacts you have, but Google has a free limit of 2500 look ups/day, so divide your contact total by that and you'll have how long it'll take to redistrict all your contacts.  If losing the lookup data you have isn't an option, which is totally reasonable, then you could hire someone to handle the migration in a more elegant way.

I hope this helps.

Joseph

**Comment by andyburnsco** [comment]
What kind of funding would you estimate for it to be maintained?

**Comment by jimcrist** [comment]
Hi Joseph,
Thanks for your thorough instructions.  I tried just uninstalling V1, deleting the files with SFTP and installing V2, but I got a DB Error when I ran the job to populate the state districts.  Just as you predicted.  So, I uninstalled V2 and deleted the electoral references I could find in the database: in civicrm_custom_field and civicrm_custom_group and dropped the tables like civicrm_value_electoral…
Then I reinstalled V2 and it gave me this:
![image](https://user-images.githubusercontent.com/30061283/59461938-2be70400-8de8-11e9-9bf5-32a291f3cedb.png)
When I ran the scheduled job I got another DB Error:
![image](https://user-images.githubusercontent.com/30061283/59462254-f1ca3200-8de8-11e9-8764-b60f0fc9b0e3.png)
![image](https://user-images.githubusercontent.com/30061283/59462305-14f4e180-8de9-11e9-87be-89bcc784597e.png)
Please Advise...thanks!
Jim

**Comment by jimcrist** [comment]
Hi Joseph,
I'd really like to get this working.  It's not initializing entity_id.  We're just a small unincorporated citizens group in Wisconsin, but maybe I could pay you out of my own pocket.  I was a programmer back in the day, but without any documentation this is hard to tackle.  The parameters for this cron job aren't even documented? Please get back to me...thanks!
Jim

**Comment by josephlacey** [comment]
Hi @jimcrist ,

I don't intend this to sound terse, but there's not enough information here to debug this error in the abstract.  Without looking at the state of the database or knowing which API call is throwing the error, like a line number from the code, there's not much advice I can offer here.  As I've said before, this is free software, so you can use it as you want and change it as you want, but I don't make any guarantees.  I'm sorry you're having problems with it, but it sounds like you need to hire someone or find a volunteer to help you debug this.  Unfortunately my capacity at the moment is full, and if I'm being totally honest, my interest in maintaining this extension has waned.

Joseph

> Hi Joseph,
> I'd really like to get this working. It's not initializing entity_id. We're just a small unincorporated citizens group in Wisconsin, but maybe I could pay you out of my own pocket. I was a programmer back in the day, but without any documentation this is hard to tackle. The parameters for this cron job aren't even documented? Please get back to me...thanks!
> Jim

**Comment by josephlacey** [comment]
Fixed with aa4fc199f853f49ddd78c87d60b3c7b52ca327b3
